# Each record should contain:
# name: (string)
# repo: (URL) location of application code
# language: main programming language of application
# description: (text) High-level overview about the resource. Format links with <a> tags.

- name: collaboratoR
  repo: https://github.com/kamclean/collaborator
  language: R
  description: Facilitates administration of multi-site investigations.

- name: REDCap-ETL
  repo: https://github.com/IUREDCap/redcap-etl
  language: PHP
  description:  Extract data from REDCap, transform the extracted data, and load the transformed data into a database.

- name: tidyREDCap
  repo: https://CRAN.R-project.org/package=tidyREDCap 
  language: R
  description: Helper functions for processing REDCap data.
