# Each record should contain:
# name: (string)
# repo: (URL) location of application code
# language: main programming language of application
# description: (text) High-level overview about the resource. Format links with <a> tags.
- name: REDCap-ETL
  repo: https://github.com/IUREDCap/redcap-etl
  language: PHP
  description:  REDCap-ETL (REDCap Extract, Transform, Load) is an application that can extract data from REDCap, transform the extracted data, and load the transformed data into a database.
